server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: yPTdI0NnWlAeB8CFrOCl7hMuLhVrt0Lq
          login:
            provider: keycloak
            client-id: admin-service
            client-secret: yPTdI0NnWlAeB8CFrOCl7hMuLhVrt0Lq
            scope:
              - metrics
              - openid
