server:
  forward-headers-strategy: native
spring:
  application:
    name: selmag-manager-app
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@host.docker.internal:8888