selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  application:
    name: selmag-manager-app

  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: W3QQD9NlFJaRkrQzyXkdTIqq1NeAndbp
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          discovery:
            provider: keycloak
            client-id: manager-app
            client-secret: W3QQD9NlFJaRkrQzyXkdTIqq1NeAndbp
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0