spring:
  boot:
    admin:
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - catalogue
      - public
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8082/realms/selmag
      client:
        registration:
          keycloak:
            client-id: catalogue-service
            client-secret: eKzXHI0ZkfSPBbHIuciGSahP9kv2SQq5
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: catalogue-service
            client-secret: eKzXHI0ZkfSPBbHIuciGSahP9kv2SQq5
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:8082/realms/selmag
logging:
  level:
    sql: info
springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://host.docker.internal:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/