server:
  port: 8761
spring:
  application:
    name: selmag-eureka-server
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:config-password@host.docker.internal:8888